server.port=9191

# Force Feign to use Eureka instead of any hardcoded URL
spring.cloud.openfeign.client.config.user-service.url=

# Make sure load balancer is enabled
spring.cloud.loadbalancer.enabled=true

# Make sure Eureka is fetching registry
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true


##Eureka server clinet kathawa
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.client.service-url.defaultZone=http://eureka.elibank.internal:8761/eureka

# Send traces to Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Sample 100% of requests (1.0 = 100%)
management.tracing.sampling.probability=1.0

#Actuator refrehs endpoints
management.endpoints.web.exposure.include=*
spring.sleuth.web.client.enabled=true
